package com.AI.ImageGenerator.Controller.Service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;

import java.util.Map;

@Service
public class ChatService {

    private final WebClient webClient;

    @Value("${gemini.api.url}")
    private String geminiApiUrl;

    @Value("${gemini.api.key}")
    private String geminiApiKey;

    public ChatService(WebClient.Builder webClientBuilder) {
        this.webClient = webClientBuilder.build();
    }

    public String generateReply(String message) {

        if (message == null || message.isBlank()) {
            return "Prompt cannot be empty";
        }

        // 🔹 Build enhanced prompt
        String prompt = buildPrompt(message);

        // 🔹 Gemini request body
        Map<String, Object> requestBody = Map.of(
                "contents", new Object[]{
                        Map.of(
                                "parts", new Object[]{
                                        Map.of("text", prompt)
                                }
                        )
                }
        );

        try {
            String response = webClient.post()
                    .uri(geminiApiUrl + geminiApiKey)
                    .header("Content-Type", "application/json")
                    .bodyValue(requestBody)
                    .retrieve()
                    .onStatus(
                            status -> status.is4xxClientError() || status.is5xxServerError(),
                            clientResponse ->
                                    clientResponse.bodyToMono(String.class)
                                            .map(body -> new RuntimeException("Gemini API error: " + body))
                    )
                    .bodyToMono(String.class)
                    .block();

            return extractResponseText(response);

        } catch (Exception e) {
            return "Error calling Gemini API: " + e.getMessage();
        }
    }

    // 🔹 Extract Gemini response safely
    private String extractResponseText(String response) {
        try {
            ObjectMapper mapper = new ObjectMapper();
            JsonNode rootNode = mapper.readTree(response);

            JsonNode candidates = rootNode.path("candidates");
            if (candidates.isMissingNode() || !candidates.isArray() || candidates.isEmpty()) {
                return "No response generated by Gemini";
            }

            return candidates.get(0)
                    .path("content")
                    .path("parts")
                    .get(0)
                    .path("text")
                    .asText();

        } catch (Exception e) {
            return "Error parsing Gemini response: " + e.getMessage();
        }
    }

    // 🔹 Prompt engineering
    private String buildPrompt(String message) {
        return """
                Improve and professionally enhance the following message.
                Keep it clear, polite, and well-structured.

                Original message:
                %s
                """.formatted(message);
    }
}
